sudo: false
git:
  depth: 1
language: ruby
bundler_args: --without development testext production --deployment --jobs=4 --retry=5
cache: bundler

rvm:
  - jruby-1.7.19

matrix:
  include:
    - { rvm: jruby-1.7.19 }

env:
  - JRUBY_OPTS="--dev" DISPLAY=:99.0 LOGGER_LEVEL=WARN

before_script: "./script/front-end-test.sh"
